apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: rocketrankbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - name: main
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: main
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: rocketrankbot
  labels:
    app: cache
spec:
  ports:
    - name: main
      port: 6379
      protocol: TCP
      targetPort: main
  selector:
    app: cache