name: Build and push trackerggscraper image

on:
  push:
    branches: ['main']
    tags: ['v*']
    paths: ['services/trackerggscraper/**']
  pull_request:
    branches: ['main']
    paths: ['services/trackerggscraper/**']

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yannismate/rbb-trackerggscraper
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: services/trackerggscraper
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}